import { query } from "@/lib/db";

/**
 * ALL SQL for notifications and reminders. Feature 09 owns this file, but it
 * is SHARED PROPERTY - it is not private to feature 09.
 *
 * Features 01 (attendance), 02 (bus), 04 (fees), 05 (groups), 06 (leaves),
 * 07 (exams) and 10 (timetable) all send notifications. NONE of them may
 * write their own notification SQL. They call lib/notify.js, which calls this
 * file. If a later feature needs a notification read that does not exist yet,
 * ADD THE FUNCTION HERE - do not duplicate a query in another repo.
 *
 * Rule (code-standards.md): every SQL statement in the app lives in
 * lib/repos/*.js, never in a route handler and never in a component.
 *
 * DB CONTRACT: no DDL and no schema changes here. The tables and indexes this
 * file depends on were created by db/schema.sql and db/migrations/003.
 *
 * TYPES RETURNED BY node-postgres, because they trip people up:
 *   id, notificationId -> BIGINT, arrives as a JavaScript STRING
 *   unreadCount        -> cast ::int in SQL, arrives as a real NUMBER
 *   createdAt, readAt  -> Date objects
 *   isRead             -> real boolean
 * Column names are aliased to camelCase here so components never touch
 * snake_case. (lib/repos/coreRepo.js predates this convention and returns raw
 * snake_case - do not copy that older style into new repos.)
 */

/**
 * The columns every notification list query returns.
 *
 * Declared once and reused by both paging branches in listForProfile() below,
 * so adding a column later means editing ONE place and the two branches can
 * never drift apart.
 */
const LIST_COLUMNS = `
		 n.id,
		 n.title,
		 n.body,
		 n.priority,
		 n.kind,
		 n.source,
		 n.link_url   AS "linkUrl",
		 n.created_at AS "createdAt",
		 r.is_read    AS "isRead",
		 r.read_at    AS "readAt"`;

/**
 * How many unread notifications one person has.
 *
 * This is the single hottest query in the whole application: every signed-in
 * browser calls it every 30 seconds to refresh the bell badge. It is served
 * entirely by the partial index idx_notif_unread, which physically contains
 * ONLY unread rows - so the work is proportional to what is unread (usually
 * 0-20 rows), never to the person's whole history.
 *
 * count(*) is a BIGINT and node-postgres would hand it back as the string
 * "5". The ::int cast makes it a real number so the badge can do arithmetic
 * and compare against 99 without a silent string comparison bug.
 *
 * @param {number|string} profileId - from the session token, never from a URL
 * @returns {Promise<number>}
 */
export async function unreadCount(profileId) {
	const result = await query(
		`SELECT count(*)::int AS count
		   FROM notification_recipients
		  WHERE profile_id = $1
			AND is_read = false`,
		[profileId]
	);
	return result.rows[0].count;
}

/**
 * One page of a person's notifications, newest first, read and unread
 * together (Gmail style - read rows stay in the list, greyed out).
 *
 * PAGING USES notification_id, NOT created_at.
 *   created_at is not unique: a broadcast writes hundreds of rows inside the
 *   same millisecond. A cursor on a non-unique column either skips rows or
 *   repeats them at the page boundary. notification_id rides the primary key,
 *   is always unique, and sorts in the same order as time because the id is
 *   generated by an ascending identity sequence.
 *
 * TWO BRANCHES, ON PURPOSE.
 *   Writing this as one statement with `($2 IS NULL OR r.notification_id < $2)`
 *   reads more cleanly but stops PostgreSQL turning the cursor into an index
 *   range scan - it degrades into "scan all of this person's rows, then
 *   filter". Two explicit statements keep both paths on
 *   idx_notif_recipient_profile(profile_id, notification_id DESC), which
 *   matches the ORDER BY exactly so the planner reads the index in order and
 *   stops after LIMIT rows instead of sorting the set.
 *
 * @param {number|string} profileId - from the session token, never from a URL
 * @param {object}   [options]
 * @param {number}   [options.limit=20]   - already clamped by the caller
 * @param {string}   [options.before]     - id of the last row of the previous
 *                                          page; omit for the first page
 * @returns {Promise<Array<object>>}
 */
export async function listForProfile(profileId, options = {}) {
	const { limit = 20, before = null } = options;

	if (before === null || before === undefined) {
		const result = await query(
			`SELECT ${LIST_COLUMNS}
			   FROM notification_recipients r
			   JOIN notifications n ON n.id = r.notification_id
			  WHERE r.profile_id = $1
			  ORDER BY r.notification_id DESC
			  LIMIT $2`,
			[profileId, limit]
		);
		return result.rows;
	}

	const result = await query(
		`SELECT ${LIST_COLUMNS}
		   FROM notification_recipients r
		   JOIN notifications n ON n.id = r.notification_id
		  WHERE r.profile_id = $1
			AND r.notification_id < $2
		  ORDER BY r.notification_id DESC
		  LIMIT $3`,
		[profileId, before, limit]
	);
	return result.rows;
}

/**
 * Mark ONE notification read for ONE person.
 *
 * SECURITY: profile_id is part of the WHERE clause, so a parent who guesses
 * another family's notification id changes nothing and gets 0 rows back. The
 * caller turns 0 rows into a 404, which deliberately does not reveal whether
 * that notification exists for somebody else.
 *
 * IDEMPOTENT: there is deliberately no `AND is_read = false` filter here.
 * With it, a second click would return 0 rows and the route would answer 404
 * for a notification the user genuinely owns. Instead the row always matches
 * if it is theirs, and COALESCE keeps the ORIGINAL read_at so a double click
 * cannot rewrite history. This matters because the bell updates optimistically
 * and can retry.
 *
 * @param {number|string} notificationId
 * @param {number|string} profileId - from the session token, never from a URL
 * @returns {Promise<boolean>} true if the row belongs to this person
 */
export async function markRead(notificationId, profileId) {
	const result = await query(
		`UPDATE notification_recipients
			SET is_read = true,
				read_at = COALESCE(read_at, now())
		  WHERE notification_id = $1
			AND profile_id = $2`,
		[notificationId, profileId]
	);
	return result.rowCount > 0;
}

/**
 * Mark every unread notification read for one person.
 *
 * `AND is_read = false` IS correct here, unlike in markRead() above. It keeps
 * the statement on the partial index idx_notif_unread and touches only rows
 * that actually change - three row writes instead of two thousand for a parent
 * with years of history. It also makes rowCount an accurate "marked N as read"
 * figure for the UI, and it protects existing read_at timestamps for free.
 *
 * @param {number|string} profileId - from the session token, never from a URL
 * @returns {Promise<number>} how many rows changed
 */
export async function markAllRead(profileId) {
	const result = await query(
		`UPDATE notification_recipients
			SET is_read = true,
				read_at = now()
		  WHERE profile_id = $1
			AND is_read = false`,
		[profileId]
	);
	return result.rowCount;
}